# Generated by Django 5.2.13 on 2026-05-04 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("permits", "0003_alter_governmentid_files"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="workpermitrequest",
            name="reviewed_at",
        ),
        migrations.RemoveField(
            model_name="workpermitrequest",
            name="reviewed_by",
        ),
        migrations.AddField(
            model_name="workpermitrequest",
            name="gm_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workpermitrequest",
            name="gm_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gm_reviewed_permits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workpermitrequest",
            name="manager_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="workpermitrequest",
            name="manager_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="manager_reviewed_permits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="governmentid",
            name="visitor_photo",
            field=models.ImageField(upload_to="visitor_photos/"),
        ),
        migrations.AlterField(
            model_name="workpermitrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_manager", "Pending Department Manager Review"),
                    ("rejected_manager", "Rejected by Department Manager"),
                    ("pending_general_manager", "Pending General Manager Review"),
                    ("rejected_general_manager", "Rejected by General Manager"),
                    ("approved", "Approved"),
                ],
                default="pending_manager",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="workpermitrequest",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_permits",
                to="permits.department",
            ),
        ),
        migrations.CreateModel(
            name="DepartmentMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("manager", "Department Manager"),
                            ("general_manager", "General Manager"),
                            ("security", "Security Personnel"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="permits.department",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
